# Generated by Django 5.2.9 on 2025-12-26 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerTraineeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was created')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this assignment', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(help_text='The trainee assigned to this trainer', limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainer', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(help_text='The trainer assigned to this trainee', limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer-Trainee Assignment',
                'verbose_name_plural': 'Trainer-Trainee Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['trainer', 'is_active'], name='users_train_trainer_1ced67_idx'), models.Index(fields=['trainee', 'is_active'], name='users_train_trainee_b4d874_idx')],
                'unique_together': {('trainer', 'trainee')},
            },
        ),
    ]
