# Generated by Django 5.2.9 on 2025-12-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trainertraineeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(help_text='Check-in time')),
                ('check_out', models.DateTimeField(blank=True, help_text='Check-out time (null if still checked in)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this attendance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Trainer or staff member who marked this attendance (null if self-check-in)', limit_choices_to={'role__in': ['TRAINER', 'MANAGER', 'OWNER', 'SUPER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(help_text='The trainee whose attendance is being tracked', limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['trainee', '-check_in'], name='users_atten_trainee_54cb8d_idx'), models.Index(fields=['check_in'], name='users_atten_check_i_6995a2_idx'), models.Index(fields=['marked_by'], name='users_atten_marked__0f3bb4_idx')],
            },
        ),
    ]
