# Generated by Django 5.2.9 on 2025-12-27 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Date of the training session')),
                ('start_time', models.TimeField(help_text='Start time of the session')),
                ('end_time', models.TimeField(help_text='End time of the session')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', help_text='Current status of the session', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this session', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the session was cancelled (if applicable)', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled the session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(help_text='The trainee for this session', limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(help_text='The trainer for this session', limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification')], default='EMAIL', help_text='Type of reminder', max_length=20)),
                ('reminder_time', models.DateTimeField(help_text='When to send the reminder')),
                ('sent', models.BooleanField(default=False, help_text='Whether the reminder has been sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the reminder was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='The training session this reminder is for', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users.trainingsession')),
            ],
            options={
                'verbose_name': 'Session Reminder',
                'verbose_name_plural': 'Session Reminders',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Start time of availability')),
                ('end_time', models.TimeField(help_text='End time of availability')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this time slot is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(help_text='The trainer whose availability this is', limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Availability',
                'verbose_name_plural': 'Trainer Availabilities',
                'ordering': ['trainer', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['trainer', 'day_of_week', 'is_available'], name='users_train_trainer_6444b9_idx')],
                'unique_together': {('trainer', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainer', 'session_date', 'status'], name='users_train_trainer_4e44d4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainee', 'session_date', 'status'], name='users_train_trainee_0cebcb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['session_date', 'start_time'], name='users_train_session_cd9bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreminder',
            index=models.Index(fields=['session', 'sent'], name='users_sessi_session_c50433_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreminder',
            index=models.Index(fields=['reminder_time', 'sent'], name='users_sessi_reminde_7b80c3_idx'),
        ),
    ]
