# Generated by Django 5.2.9 on 2025-12-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the theme (e.g., 'Emerald', 'Blue', 'Purple')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the theme', max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default theme')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this theme is available for selection')),
                ('primary_color', models.CharField(default='#10b981', help_text='Primary color in hex format (e.g., #10b981)', max_length=7)),
                ('primary_color_dark', models.CharField(default='#059669', help_text='Darker shade of primary color', max_length=7)),
                ('primary_color_light', models.CharField(default='#34d399', help_text='Lighter shade of primary color', max_length=7)),
                ('secondary_color', models.CharField(default='#14b8a6', help_text='Secondary color in hex format', max_length=7)),
                ('secondary_color_dark', models.CharField(default='#0d9488', help_text='Darker shade of secondary color', max_length=7)),
                ('secondary_color_light', models.CharField(default='#5eead4', help_text='Lighter shade of secondary color', max_length=7)),
                ('primary_tailwind', models.CharField(default='emerald', help_text="Tailwind color name for primary (e.g., 'emerald', 'blue', 'purple')", max_length=50)),
                ('secondary_tailwind', models.CharField(default='teal', help_text='Tailwind color name for secondary', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the theme', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='site_settings', editable=False, help_text='Singleton identifier to ensure only one settings instance exists', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(blank=True, help_text='Site-wide theme preference (null means use default theme)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='core.theme')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
