# Generated by Django 5.2.9 on 2025-12-26 10:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], help_text='Plan name', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Plan description and features')),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_days', models.IntegerField(default=30, help_text='Subscription duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this plan')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', help_text='Subscription status', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Subscription start date')),
                ('end_date', models.DateTimeField(help_text='Subscription end date')),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether subscription should auto-renew')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Membership plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membershipplan')),
                ('user', models.ForeignKey(help_text='Subscribed user', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', help_text='Payment method used', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of payment')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(help_text='Associated subscription', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='memberships.subscription')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='memberships_user_id_95313c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='memberships_end_dat_86390f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'status'], name='memberships_subscri_7bae40_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='memberships_payment_00bc37_idx'),
        ),
    ]
